services:
  mysql_db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=whoknows
    volumes:
      - mysql_data:/var/lib/mysql # Named volume for data persistence
    ports:
      - 3307:3306
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 1

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: no
    ports:
      - 8080:8080
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - mynetwork
    volumes:
      - ./frontend:/app/frontend
      - ./backend:/app/backend

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:
# when done docker compose down
