# Backend Development Dockerfile
FROM golang:1.23 AS builder

# Install Air for live reloading
RUN go install github.com/air-verse/air@latest

# Set the current working directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Copy the Go app source code to the container
COPY . .

# Command to run Air for hot reloading
CMD ["air"]
