name: deploy
on:
  push:
    branches:
      - main

jobs:
  get_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_output.outputs.version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

  build_and_push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_build_image_tag.outputs.image_tag }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log into GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set Repository Name to Lowercase
        id: set_repo_name
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "repo_name=$REPO_NAME" >> $GITHUB_ENV

      - name: Build and Push Image
        env:
          repo_name: ${{ env.repo_name }}
        run: |
          docker build -t ghcr.io/${{ env.repo_name }}:latest -f ./src/Dockerfile.prod ./src
          docker push ghcr.io/${{ env.repo_name }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    env:
      IMAGE_TAG: ${{ needs.build_and_push.outputs.image_tag }}
    steps:
      - name: Set Repository Name to Lowercase
        id: set_repo_name
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "repo_name=$REPO_NAME" >> $GITHUB_ENV

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to AWS EC2 instance
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          REPO_NAME: ${{ env.repo_name }}
        run: |
          echo "Deploying with IMAGE_TAG: ${{ env.IMAGE_TAG }}"

          # SSH into AWS EC2 instance
          ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_USER }}@${{ secrets.AWS_IP }} << EOF
            cd /whoknows || exit

            # log into GitHub Container Registry
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Pull the compose.prod.yml
            git fetch origin main
            git checkout origin/main -- compose.prod.yml

            # Set environment variables directly in OS (no need for .env)
            export ENV_DATABASE_USER="${{ secrets.ENV_DATABASE_USER }}"
            export ENV_DATABASE_PASSWORD="${{ secrets.ENV_DATABASE_PASSWORD }}"
            export ENV_DATABASE_NAME="${{ secrets.ENV_DATABASE_NAME }}"
            export ENV_DATABASE_SSLMODE="${{ secrets.API_DATABASE_SSL_MODE }}"
            export ENV_DATABASE_MIGRATE="${{ secrets.ENV_DATABASE_MIGRATE }}"
            export ENV_JWT_SECRET="${{ secrets.ENV_JWT_SECRET }}"
            export ENV_JWT_EXPIRY="${{ secrets.ENV_JWT_EXPIRY }}"
            export ENV_WEATHER_API_KEY="${{ secrets.ENV_WEATHER_API_KEY }}"
            export IMAGE_TAG="${{ env.IMAGE_TAG }}"
            export IMAGE_VERSION="${{ env.IMAGE_TAG }}"
            export ENV_MONITOR_IP="${{ secrets.ENV_MONITOR_IP }}"

            # Pull the latest images from GHCR
            echo "Pulling image ghcr.io/${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }}"
            docker pull ghcr.io/${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }}

            # Start Docker services for production
            echo "Starting Docker services for production..."
            docker compose -f compose.prod.yml down
            docker compose -f compose.prod.yml up -d
          EOF

      - name: Clean up unused images
        run: |
          docker image prune -f