name: Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:
  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH
        run: sudo apt-get install openssh-client
        
      - name: Import EC2 SSH Key
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_SSH_KEY" > ec2_ssh_key.pem
          chmod 600 ec2_ssh_key.pem

      - name: Copy code to EC2
        run: scp -i ec2_ssh_key.pem -r ${{ github.workspace }} ubuntu@ec2-${{ secrets.EC2_IP_ADDRESS }}:/whoknows

      - name: SSH into EC2 and run commands
        run: |
          ssh -i ec2_ssh_key.pem ubuntu@ec2-${{ secrets.EC2_IP_ADDRESS }} << EOF
            cd /whoknows
            docker-compose down
            docker-compose up -d
          EOF