name: Deploy Go Project to Azure VM

on:
  push:
    branches:
      - main  # Deploy on pushes to main branch
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23  # Set the Go version you need

      # Step 3: Build the Go project
      - name: Build Go application
        working-directory: ./backend  # Ensure the correct working directory
        run: |
          go mod tidy
          go build -o myapp ./main.go  # Adjust to match your project's entry point

      # Step 4: Set up SSH key and known hosts
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.10.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 5: Add known hosts
      - name: Add known hosts
        run: |
          echo "${{ secrets.AZURE_VM_IP }} ssh-ed25519 $(ssh-keyscan -t ed25519 ${{ secrets.AZURE_VM_IP }})" >> ~/.ssh/known_hosts

      # Step 6: Transfer the binary to the Azure VM using scp
      - name: Copy binary to Azure VM
        run: |
          scp -o StrictHostKeyChecking=no ./backend/myapp ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }}:${{ secrets.VM_PROJECT_DIR }}

      # Step 7: Restart application on Azure VM
      - name: Restart application on Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
          sudo systemctl stop myapp.service || true  # Stop existing service if it exists
          sudo mv ${VM_PROJECT_DIR}/myapp /usr/local/bin/myapp  # Move binary to final directory
          sudo chmod +x /usr/local/bin/myapp  # Ensure it's executable
          sudo systemctl start myapp.service  # Start or restart the app
          EOF
